#!/usr/bin/env bash

# Adpated from thoughtbot's laptop script.
# https://github.com/thoughtbot/laptop

laptop_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n[LAPTOP] $fmt\\n" "$@"
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "${HOME}/bin/" ]; then
  mkdir "${HOME}/bin"
fi

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "${LOGNAME}:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "${LOGNAME}:admin" "$HOMEBREW_PREFIX"
fi

update_fish_shell() {
  local shell_path;
  shell_path="$(command -v fish)"

  laptop_echo "Changing your shell to fish ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    laptop_echo "Adding '${shell_path}' to /etc/shells"
    echo "$shell_path" | sudo tee -a /etc/shells
  fi
  sudo chsh -s "$shell_path" "$USER"
}

update_zsh_shell() {
  local shell_path;
  shell_path="$(command -v zsh)"

  laptop_echo "Changing your shell to zsh ..."
  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
    laptop_echo "Adding '${shell_path}' to /etc/shells"
    sudo sh -c "echo ${shell_path} >> /etc/shells"
  fi
  sudo chsh -s "$shell_path" "$USER"
}

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

if ! command -v brew >/dev/null; then
  laptop_echo "Installing Homebrew ..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

if brew list | grep -Fq brew-cask; then
  laptop_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

laptop_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# Need to install openssl before libyaml
brew "openssl"
brew "openssl@1.1" # wget dependency

brew "awscli"
brew "jq"
brew "ssh-copy-id"
brew "tmux"
brew "tree"
brew "wget"
brew "youtube-dl"

# homebrew-cask
# https://github.com/caskroom/homebrew-cask
cask "iterm2"
cask "google-chrome"
cask "google-cloud-sdk"
cask "spotify"
cask "vlc"
cask "visual-studio-code"
EOF

case "$DEFAULT_SHELL" in
  fish)
    laptop_echo "Your shell preference is set to FISH..."
    update_fish_shell
    ;;
  zsh)
    laptop_echo "Your shell preference is set to ZSH..."
    update_zsh_shell
    ;;
  *)
    laptop_echo "No shell preference detected. Using FISH..."
    update_fish_shell
    ;;
esac

echo_ok "Installing VS Code Extensions..."

VSCODE_EXTENSIONS=(
	betterthantomorrow.calva
  2gua.rainbow-brackets
  heptio.jsonnet
  borkdude.clj-kondo
)

if hash code &>/dev/null; then
	echo_ok "Installing VS Code extensions..."
	for i in "${VSCODE_EXTENSIONS[@]}"; do
		code --install-extension "$i"
	done
fi

laptop_echo "Laptop installation completed successfully!"
